household_power_consumption <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
filter <- c("1/2/2007","2/2/2007")
household_subset <- subset(household_power_consumption, Date %in% filter)
household_subset$DateTime <- as.POSIXct(paste(household_subset$Date, household_subset$Time), format="%Y-%m-%d %H:%M:%S")
png(file = "plot4.png", bg = "white", width=480, height=480)
opar=par(ps=12, mfrow=c(2,2))
plot(household_subset$DateTime,household_subset$Global_active_power, type="l",ylab="Global Active Power", xlab="")
plot(household_subset$DateTime,household_subset$Voltage, type="l", ylab=colnames(household_subset)[5],xlab="datetime")
plot(household_subset$DateTime,household_subset$Sub_metering_1, type="l",ylab="Energy sub metering", xlab="")
lines(household_subset$DateTime,household_subset$Sub_metering_2,col="red")
lines(household_subset$DateTime,household_subset$Sub_metering_3,col="blue")
legend("topright",legend=colnames(household_subset)[7:9],col=c("black","red","blue"),lty=1, bty="n")
plot(household_subset$DateTime,household_subset$Global_reactive_power, type="l",ylab=colnames(household_subset)[4],xlab="datetime")
dev.off()