household_power_consumption <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
filter <- c("1/2/2007","2/2/2007")
household_subset <- subset(household_power_consumption, Date %in% filter)
household_subset$DateTime <- as.POSIXct(paste(household_subset$Date, household_subset$Time), format="%Y-%m-%d %H:%M:%S")
png(file = "plot3.png", bg = "white", width=480, height=480)
opar=par(ps=12)
plot(household_subset$DateTime,household_subset$Sub_metering_1, type="l",ylab="Energy sub metering", xlab="")
lines(household_subset$DateTime,household_subset$Sub_metering_2,col="red")
lines(household_subset$DateTime,household_subset$Sub_metering_3,col="blue")
legend("topright",legend=colnames(household_subset)[7:9],col=c("black","red","blue"),lty=1)
dev.off()