household_power_consumption <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
filter <- c("1/2/2007","2/2/2007")
household_subset <- subset(household_power_consumption, Date %in% filter)
png(file = "plot1.png", bg = "white", width=480, height=480)
opar=par(ps=12)
hist(household_subset$Global_active_power, col="red", xlab="Global Active Power (kilowatts)", ylab="Frequency", xlim=c(0,8), axes=F, main="Global Active Power")
axis(1, at=c(0,2,4,6))
axis(2, at=c(0,200,400,600,800,1000,1200))
dev.off()